#!/bin/bash
for file in templates/*.mustache; do
    file="$(basename $file)"
    name="$(cut -d'.' -f1 <<<"$file")"
    mustache -p templates/partials/nav.mustache dataView.json templates/$name.mustache ../$name.html
done
